### PR TITLE
Feature: <Behavior>

### PR DESCRIPTION
**Pull request by hookex**
#### new Feature: <Behavior>
- generate behavior class
- `pointerDragBehavior` story

PS: Code diff is strange.
My code editor is WebStorm and I will check what caused it next time.

### CODE REVIEW

**Comment by brianzinn** [comment]
@hookex  This looks really great!!  Why did you close?

**Comment by hookex** [comment]
> @hookex This looks really great!! Why did you close?

I'm checking the diff and commit problem.

**Comment by brianzinn** [comment]
ok - I can merge as a squash commit, if you want to re-open :)

**Comment by hookex** [comment]
> ok - I can merge as a squash commit, if you want to re-open :)

Ok, maybe I pushed from the old repository.

**Comment by brianzinn** [comment]
oops, I can't anymore because you deleted the repository...

**Comment by hookex** [comment]
> oops, I can't anymore because you deleted the repository...

new PR has pushed :)

**Pull request closed without merging**
