### PR TITLE
[fix] Topic rendering

### PR DESCRIPTION
**Pull request by benallfree**
Stacked on #195.

Fixes topic rendering.

Ready to merge 👍 

Continuing on with killer demos now!

### CODE REVIEW

**Comment by brianzinn** [comment]
hi @benallfree - looks like you are still working on this.  let me know when it's good.  this branch has conflicts as well if you can manage that - thanks.  i'm getting it running here locally... lots of changes!! 😄

**Comment by benallfree** [comment]
I'll keep it in draft mode til it's ready 👍

**Comment by brianzinn** [comment]
Have you followed this:
https://www.clever-cloud.com/blog/features/2022/01/11/security-update-about-colors-and-faker/

Now I see why the colors deps are 404ing!  Interesting comments on the github issues for them too.

**Comment by benallfree** [comment]
Ok this PR is ready to go.

**Pull request merged**
