### PR TITLE
feat: add support for PhysicsAggregate

### PR DESCRIPTION
**Pull request by pjoe**
I have used BJS 6.26.0 for `generate-code` and have physics v2 working in a small sample.

Managed to add example to the gatsby site as well on the existing Physics page (for now kept the v1 version below).

### CODE REVIEW

**Comment by pjoe** [comment]
Would be fantastic to get this released in time for a workshop tomorrow AM (CEST), where I'm introducing BJS and react-babylonjs to our devs 🙏

**Comment by brianzinn** [comment]
I will merge this today and publish. Thank you for your contribution. Is it ok if add you to main page readme? Would be great to have a havok example. Cheers

**Comment by pjoe** [comment]
Sure, you can add me to the README, I added a Havok sample to the gatsby site in the second commit here (just ported the v1/Cannon sample to v2/Havok). Also working on a starter Codesandbox for the workshop, that I can share afterwards. As many of our devs already know React, I think this will be a great way to introduce BJS.

**Comment by brianzinn** [comment]
@pjoe your addition is published.  the github action to build the gatsby website failed, but I ran the release anyway `3.1.24`.  Hope that works for you.

It's building locally, but I'll leave the website for another day (it was working yesterday!)... 😄 
https://github.com/brianzinn/react-babylonjs/actions/runs/6659366126/job/18098275890

**Comment by pjoe** [comment]
@brianzinn Thank you so much 🙏, made it just in time for the workshop - which went well. Always tricky when you wanna show so much and get participants to have some hand on too, in a very limited time.

Oh, and CI is always fun - especially when it seems to behave differently from local 😄

**Pull request merged**
