### PR TITLE
get storybook to run and npm audit

### PR DESCRIPTION
**Pull request by konsumer**
This is a `npm audit` (only fixed 2/24 vulns, so more manual fixes should be applied) and makes storybook work out of the box (clone repo, run `npm i`, then `npm run storybook`)

I didn't fix anything  with #134 so I still needed the `--legacy-peer-deps` flag.

### CODE REVIEW

**Comment by konsumer** [comment]
Maybe it would be better to keep `"type": "module"` and fix the `require('path')` in .storybook/main.js?

**Comment by konsumer** [comment]
Just renaming main.js to main.cjs seems to fix it, while keeping `"type": "module"`

**Review by brianzinn — APPROVED** [review]
thanks @konsumer - i always manually build storybook before running.  intention is to move storybook into a subdirectory with own package.json as most of those dev dependencies have no bearing on the main project itself :)

**Comment by konsumer** [comment]
>  intention is to move storybook into a subdirectory with own package.json as most of those dev dependencies have no bearing on the main project itself :)

Yeh, that is a good call. This is fairly minimal impact, for now, but that seems like a better solution.

**Comment by konsumer** [comment]
I bet we could even replace `../../../dist/react-babylonjs` with [aliases](https://webpack.js.org/configuration/resolve/) so it can work as a standalone package, and also work in-tree, if you want them to still work together (which would be handier for adding new features to react-bablyonjs, as you will get full-rebuilds of the library, too.)

**Pull request merged**
