### PR TITLE
Adding Storybook and Dynamic Terrain

### PR DESCRIPTION
**Pull request by seacloud9**
- Adding dynamic terrain
- integrating storybook to make it easier for people learning how to use babylon-react

### CODE REVIEW

**Comment by brianzinn** [comment]
wow @seacloud9  - this is a great contribution!!  Always wanted to add storybook, but kept putting it off.  I will have a look through this and merge, but it will take me till the weekend as lots of files changed :)

I haven't used dynamic terrain before, so going to look through that.  Looks cool!  Thanks again.

**Comment by seacloud9** [comment]
@brianzinn no problem.  Let me know any changes I can make.  It might also be nice to eventually get this supported within the main babylonJS repo.  This I think would help with adoption.  Lots of people are [interested in this](https://twitter.com/seacloud9/status/1142992339318661120).  In my humble opinion this has the opportunity to become more popular than aFrame. 

I might also add a plugin to storybook that allows people to copy and paste / reveal code.

**Comment by brianzinn** [comment]
Thanks.  It looks really good except that the storyboard iframe doesn't look right on my Macbook Chrome:
image
The height is not enough, while it stretches the whole width.  It looks good on the video in your tweet...  other than that will be able to merge!  Thanks for the kind words - I think that BabylonJS has a lot of potential, too :)

**Comment by seacloud9** [comment]
Awesome.  I will take a look tonight and resolve the issue :)

**Comment by seacloud9** [comment]
I have updated me storybook integration I am going to close this push and submit a new one that solves all issues.

**Comment by seacloud9** [comment]
@brianzinn height should now no longer be an issue with the new PR also added view source addon. 

I had to add another demo to show how you can easily use GSAP with react-babylon ;)

**Pull request closed without merging**
